### ISSUE TITLE
Can't select an option

### ISSUE THREAD

**Issue by chevyphillip** [adamjsturge/easy-xsshunter-express#1]
<img width="1728" alt="Screenshot 2023-03-21 at 12 30 38 PM" src="https://user-images.githubusercontent.com/49420050/226677030-292d8a1c-1086-46ac-8b2d-2434102af1c1.png">

**Comment by hpy** [comment]
See fix here: https://github.com/adamjsturge/easy-xsshunter-express/pull/2/commits/80e209798f7b7a791b5c76bd425c2b41811778bc
